apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robo-app-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: robo-app-dev
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: environments/dev
    repoURL: https://github.com/basavaraju-g/robot-shop-demo
    targetRevision: master
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
